"""
ValidDoc blockchain service — Polygon Amoy Testnet.

Loads ABI from blockchain/ValidDocRegistry_abi.json (generated by deploy.py).
All blockchain calls are wrapped in try/except; if the RPC is unreachable the
caller receives status="pending_chain" so the document is still saved locally.
"""

import hashlib
import json
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

# ABI lives alongside the contract, one level above backend/
_ABI_PATH = Path(__file__).parent.parent.parent / "blockchain" / "ValidDocRegistry_abi.json"


def _load_abi():
    try:
        return json.loads(_ABI_PATH.read_text())
    except Exception as e:
        logger.error("Cannot load ABI from %s: %s", _ABI_PATH, e)
        return None


class BlockchainService:
    def __init__(self):
        self._ready = False
        rpc_url = os.getenv("POLYGON_RPC_URL")
        private_key = os.getenv("POLYGON_PRIVATE_KEY")
        contract_address = os.getenv("CONTRACT_ADDRESS")

        if not rpc_url or not private_key or not contract_address:
            logger.warning("Blockchain env vars missing — ValidDoc will save locally only")
            return
        if private_key == "your_wallet_private_key_here":
            logger.warning("POLYGON_PRIVATE_KEY not set — ValidDoc will save locally only")
            return

        abi = _load_abi()
        if abi is None:
            return

        try:
            from web3 import Web3
            from eth_account import Account

            self._w3 = Web3(Web3.HTTPProvider(rpc_url))
            checksum_addr = Web3.to_checksum_address(contract_address)
            self._contract = self._w3.eth.contract(address=checksum_addr, abi=abi)
            self._account = Account.from_key(private_key)
            self._ready = True
            logger.info("BlockchainService ready. Contract: %s", checksum_addr)
        except Exception as e:
            logger.error("BlockchainService init failed: %s", e)

    @property
    def is_ready(self) -> bool:
        return self._ready

    def store_document(self, file_bytes: bytes, doc_type: str) -> dict:
        """
        Hash file_bytes with SHA-256, store on chain.
        Returns dict with status, hash, tx_hash, polygonscan_url, block.
        On any failure returns status='pending_chain' — caller must handle gracefully.
        """
        doc_hash = hashlib.sha256(file_bytes).hexdigest()

        if not self._ready:
            return {"status": "pending_chain", "hash": doc_hash, "tx_hash": None, "polygonscan_url": None}

        try:
            if not self._w3.is_connected():
                raise ConnectionError("RPC unreachable")

            # Check if already registered
            exists, timestamp, _ = self._contract.functions.verifyDocument(doc_hash).call()
            if exists:
                contract_addr = os.getenv("CONTRACT_ADDRESS", "")
                return {
                    "status": "already_registered",
                    "hash": doc_hash,
                    "tx_hash": None,
                    "polygonscan_url": f"https://amoy.polygonscan.com/address/{contract_addr}",
                    "chain_timestamp": timestamp,
                }

            nonce = self._w3.eth.get_transaction_count(self._account.address)
            tx = self._contract.functions.storeDocument(doc_hash, doc_type).build_transaction({
                "from": self._account.address,
                "nonce": nonce,
                "gasPrice": self._w3.eth.gas_price,
            })
            signed = self._w3.eth.account.sign_transaction(tx, self._account.key)
            tx_hash_bytes = self._w3.eth.send_raw_transaction(signed.raw_transaction)
            receipt = self._w3.eth.wait_for_transaction_receipt(tx_hash_bytes, timeout=120)

            tx_hash_hex = tx_hash_bytes.hex()
            return {
                "status": "success",
                "hash": doc_hash,
                "tx_hash": tx_hash_hex,
                "polygonscan_url": f"https://amoy.polygonscan.com/tx/{tx_hash_hex}",
                "block": receipt.blockNumber,
                "chain_timestamp": None,
            }

        except Exception as e:
            logger.error("Blockchain store_document failed: %s", e)
            return {"status": "pending_chain", "hash": doc_hash, "tx_hash": None, "polygonscan_url": None}

    def verify_document(self, file_bytes: bytes) -> dict:
        """
        Re-hash file_bytes and call verifyDocument on chain.
        Returns dict with verified bool + chain metadata.
        On failure returns verified=None (indeterminate).
        """
        doc_hash = hashlib.sha256(file_bytes).hexdigest()
        contract_addr = os.getenv("CONTRACT_ADDRESS", "")

        if not self._ready:
            return {
                "verified": None,
                "hash": doc_hash,
                "error": "blockchain_unavailable",
                "polygonscan_url": f"https://amoy.polygonscan.com/address/{contract_addr}",
            }

        try:
            if not self._w3.is_connected():
                raise ConnectionError("RPC unreachable")

            exists, timestamp, doc_type = self._contract.functions.verifyDocument(doc_hash).call()
            return {
                "verified": exists,
                "hash": doc_hash,
                "doc_type": doc_type if exists else None,
                "chain_timestamp": timestamp if exists else None,
                "polygonscan_url": f"https://amoy.polygonscan.com/address/{contract_addr}",
            }

        except Exception as e:
            logger.error("Blockchain verify_document failed: %s", e)
            return {
                "verified": None,
                "hash": doc_hash,
                "error": str(e),
                "polygonscan_url": f"https://amoy.polygonscan.com/address/{contract_addr}",
            }


# Singleton — imported once, reused across requests
blockchain_service = BlockchainService()
